# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

osc1337_ <- function(file, bg, width, height, pointsize, standalone, aliases) {
    .Call(`_osc1337_osc1337_`, file, bg, width, height, pointsize, standalone, aliases)
}

